import nltk
from nltk.classify import NaiveBayesClassifier
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import pickle

class IntentionIdentifier:

    def __init__(self):
        nltk.download('punkt')
        nltk.download('stopwords')
        print(":Intention Identifier Started Successfully:")

    # Função para extrair recursos de uma mensagem
    def extract_features(self, message):
        words = word_tokenize(message)
        words = [word.lower() for word in words if word.isalpha() and word.lower() not in stopwords.words('english')]
        return dict([(word, True) for word in words])
    
    def train_data(self):
        training_data = [
            (self.extract_features("Como estará o clima na próxima segunda-feira?"), "previsão_do_tempo"),
            (self.extract_features("Vai fazer calor no final de semana?"), "previsão_do_tempo"),
            (self.extract_features("Será que vai chover amanhã à noite?"), "previsão_do_tempo"),
            (self.extract_features("Dê-me a previsão para os próximos 5 dias."), "previsão_do_tempo"),
            (self.extract_features("Qual é a temperatura máxima esperada para hoje?"), "previsão_do_tempo"),
            (self.extract_features("Preveja as condições climáticas para a próxima primavera."), "previsão_do_tempo"),
            (self.extract_features("Vai nevar durante o inverno?"), "previsão_do_tempo"),
            (self.extract_features("Como estará o tempo na praia amanhã?"), "previsão_do_tempo"),
            (self.extract_features("Qual será a temperatura mínima nesta noite?"), "previsão_do_tempo"),
            (self.extract_features("Previsão para o mês de julho?"), "previsão_do_tempo"),
            (self.extract_features("Será que teremos um verão quente este ano?"), "previsão_do_tempo"),
            (self.extract_features("Como estará o clima no hemisfério sul durante o outono?"), "previsão_do_tempo"),
            (self.extract_features("Previsão do tempo para a região central do país."), "previsão_do_tempo"),
            (self.extract_features("Vai ventar forte amanhã?"), "previsão_do_tempo"),
            (self.extract_features("Dê-me informações sobre a previsão do tempo para a próxima semana."), "previsão_do_tempo"),
            (self.extract_features("O que os meteorologistas preveem para o próximo mês?"), "previsão_do_tempo"),
            (self.extract_features("Como estará o tempo nas montanhas amanhã?"), "previsão_do_tempo"),
            (self.extract_features("Vai chover no norte do país?"), "previsão_do_tempo"),
            (self.extract_features("Qual é a previsão para o clima na região costeira?"), "previsão_do_tempo"),
            (self.extract_features("Será que teremos um inverno rigoroso este ano?"), "previsão_do_tempo"),
            (self.extract_features("Previsão para a próxima temporada de furacões."), "previsão_do_tempo"),
            (self.extract_features("Como estará o clima na cidade grande amanhã?"), "previsão_do_tempo"),
            (self.extract_features("Vai haver tempestade durante a primavera?"), "previsão_do_tempo"),
            (self.extract_features("Dê-me a previsão para o próximo feriado."), "previsão_do_tempo"),
            (self.extract_features("Será que teremos um verão chuvoso?"), "previsão_do_tempo"),
            (self.extract_features("Previsão do tempo para eventos ao ar livre neste fim de semana."), "previsão_do_tempo"),
            (self.extract_features("Vai fazer frio nas montanhas russas amanhã?"), "previsão_do_tempo"),
            (self.extract_features("Como estará o tempo na região sul durante o inverno?"), "previsão_do_tempo"),
            (self.extract_features("Previsão para a próxima semana de férias."), "previsão_do_tempo"),
            (self.extract_features("Vai nevar em lugares mais altos amanhã?"), "previsão_do_tempo"),
            (self.extract_features("Qual será a temperatura média para este mês?"), "previsão_do_tempo"),
            (self.extract_features("Previsão do tempo para o litoral no próximo mês."), "previsão_do_tempo"),
            (self.extract_features("Vai fazer calor no deserto amanhã?"), "previsão_do_tempo"),
            (self.extract_features("Como estará o clima na zona rural amanhã?"), "previsão_do_tempo"),
            (self.extract_features("Vai chover no sul do país durante o verão?"), "previsão_do_tempo"),
            (self.extract_features("Previsão para a próxima semana de eventos esportivos ao ar livre."), "previsão_do_tempo"),
            (self.extract_features("Vai fazer sol no feriado?"), "previsão_do_tempo"),
            (self.extract_features("Qual é a previsão para o clima na próxima primavera?"), "previsão_do_tempo"),
            (self.extract_features("Previsão do tempo para o próximo festival de música."), "previsão_do_tempo"),
            (self.extract_features("Vai haver neblina na cidade amanhã de manhã?"), "previsão_do_tempo"),
            (self.extract_features("Como estará o clima na estação de esqui amanhã?"), "previsão_do_tempo"),
            (self.extract_features("Previsão para o próximo mês de viagens."), "previsão_do_tempo"),
            (self.extract_features("Vai chover durante o carnaval?"), "previsão_do_tempo"),
            (self.extract_features("Qual é a previsão para o clima no hemisfério norte durante o verão?"), "previsão_do_tempo"),
            (self.extract_features("Previsão do tempo para o próximo dia dos namorados."), "previsão_do_tempo"),
            (self.extract_features("Vai fazer calor na região central amanhã?"), "previsão_do_tempo"),
            (self.extract_features("Como estará o clima na próxima maratona?"), "previsão_do_tempo"),
            (self.extract_features("Previsão para o próximo festival de gastronomia."), "previsão_do_tempo"),
            (self.extract_features("Vai chover durante a semana de moda?"), "previsão_do_tempo"),
            (self.extract_features("Traduza 'world' para o alemão."), "tradução"),
            (self.extract_features("O que significa 'amour' em francês?"), "tradução"),
            (self.extract_features("Como se diz 'house' em japonês?"), "tradução"),
            (self.extract_features("Traduza esta frase para o russo."), "tradução"),
            (self.extract_features("Qual é a tradução de 'casa' para o italiano?"), "tradução"),
            (self.extract_features("Dê-me a tradução de 'hello' para o espanhol."), "tradução"),
            (self.extract_features("O que 'amigo' significa em chinês?"), "tradução"),
            (self.extract_features("Como se diz 'obrigado' em árabe?"), "tradução"),
            (self.extract_features("Traduza 'cat' para o sueco."), "tradução"),
            (self.extract_features("O que 'love' quer dizer em turco?"), "tradução"),
            (self.extract_features("Como se expressa 'goodbye' em grego?"), "tradução"),
            (self.extract_features("Traduza 'computer' para o coreano."), "tradução"),
            (self.extract_features("O que é 'moon' em hindi?"), "tradução"),
            (self.extract_features("Como se fala 'time' em vietnamita?"), "tradução"),
            (self.extract_features("Traduza 'happy' para o polonês."), "tradução"),
            (self.extract_features("O que 'soleil' significa em italiano?"), "tradução"),
            (self.extract_features("Como se diz 'water' em holandês?"), "tradução"),
            (self.extract_features("Traduza 'book' para o hebraico."), "tradução"),
            (self.extract_features("O que 'amor' quer dizer em português?"), "tradução"),
            (self.extract_features("Como se expressa 'good morning' em alemão?"), "tradução"),
            (self.extract_features("Traduza 'tree' para o finlandês."), "tradução"),
            (self.extract_features("O que 'cielo' significa em espanhol?"), "tradução"),
            (self.extract_features("Como se fala 'friend' em francês?"), "tradução"),
            (self.extract_features("Traduza 'sky' para o japonês."), "tradução"),
            (self.extract_features("O que 'sole' quer dizer em italiano?"), "tradução"),
            (self.extract_features("Como se diz 'computer' em russo?"), "tradução"),
            (self.extract_features("Traduza 'night' para o chinês."), "tradução"),
            (self.extract_features("O que 'merci' significa em francês?"), "tradução"),
            (self.extract_features("Como se expressa 'hello' em árabe?"), "tradução"),
            (self.extract_features("Traduza 'heart' para o coreano."), "tradução"),
            (self.extract_features("O que 'neige' quer dizer em francês?"), "tradução"),
            (self.extract_features("Como se fala 'sun' em espanhol?"), "tradução"),
            (self.extract_features("Traduza 'family' para o alemão."), "tradução"),
            (self.extract_features("O que 'maison' significa em francês?"), "tradução"),
            (self.extract_features("Como se diz 'computer' em chinês?"), "tradução"),
            (self.extract_features("Traduza 'water' para o hindi."), "tradução"),
            (self.extract_features("O que 'amigo' quer dizer em português?"), "tradução"),
            (self.extract_features("Como se expressa 'book' em italiano?"), "tradução"),
            (self.extract_features("Traduza 'sun' para o russo."), "tradução"),
            (self.extract_features("O que 'casa' significa em espanhol?"), "tradução"),
            (self.extract_features("Como se fala 'hello' em francês?"), "tradução"),
            (self.extract_features("Traduza 'world' para o italiano."), "tradução"),
            (self.extract_features("O que 'amor' quer dizer em espanhol?"), "tradução"),
            (self.extract_features("Como se diz 'water' em alemão?"), "tradução"),
            (self.extract_features("Traduza 'time' para o português."), "tradução"),
            (self.extract_features("O que 'soleil' significa em francês?"), "tradução"),
            (self.extract_features("Como se expressa 'happy' em chinês?"), "tradução"),
            (self.extract_features("Traduza 'cat' para o espanhol."), "tradução"),
            (self.extract_features("O que 'book' quer dizer em inglês?"), "tradução"),
            (self.extract_features("Como se diz 'family' em russo?"), "tradução"),
            (self.extract_features("Traduza 'tree' para o francês."), "tradução"),
            (self.extract_features("O que 'heart' significa em inglês?"), "tradução"),
            (self.extract_features("Como se fala 'night' em italiano?"), "tradução"),
            (self.extract_features("Traduza 'sun' para o chinês."), "tradução"),
            (self.extract_features("O que 'sole' quer dizer em italiano?"), "tradução"),
            (self.extract_features("Como se diz 'merci' em inglês?"), "tradução"),
            (self.extract_features("Traduza 'hello' para o japonês."), "tradução"),
            (self.extract_features("O que você está fazendo agora?"), "outros"),
            (self.extract_features("Dê-me uma receita de bolo."), "outros"),
            (self.extract_features("Conte-me uma piada engraçada."), "outros"),
            (self.extract_features("Explique o conceito de inteligência artificial."), "outros"),
            (self.extract_features("Quais são os benefícios do exercício físico?"), "outros"),
            (self.extract_features("Qual é a capital da França?"), "outros"),
            (self.extract_features("Quantos planetas existem no sistema solar?"), "outros"),
            (self.extract_features("Quem é o presidente do Brasil?"), "outros"),
            (self.extract_features("Como se chama a maior montanha do mundo?"), "outros"),
            (self.extract_features("Como se reproduzem as baleias?"), "outros"),
            (self.extract_features("Quem escreveu 'Romeu e Julieta'?"), "outros"),
            (self.extract_features("O que é a teoria da relatividade?"), "outros"),
            (self.extract_features("Como posso aprender a tocar guitarra?"), "outros"),
            (self.extract_features("Quem ganhou o prêmio Nobel da Paz em 2020?"), "outros"),
            (self.extract_features("Explique o processo de fotossíntese."), "outros"),
            (self.extract_features("Qual é a diferença entre mitose e meiose?"), "outros"),
            (self.extract_features("Como começar a aprender programação?"), "outros"),
            (self.extract_features("Quem foi Cleópatra?"), "outros"),
            (self.extract_features("O que é a lei da oferta e da procura?"), "outros"),
            (self.extract_features("Explique a teoria do Big Bang."), "outros"),
            (self.extract_features("O que é a inteligência emocional?"), "outros"),
            (self.extract_features("Quais são os sintomas da gripe?"), "outros"),
            (self.extract_features("Qual é a diferença entre hardware e software?"), "outros"),
            (self.extract_features("Como posso melhorar minhas habilidades de comunicação?"), "outros"),
            (self.extract_features("Quais são os efeitos do aquecimento global?"), "outros"),
            (self.extract_features("O que é a síndrome de impostor?"), "outros"),
            (self.extract_features("Quais são os sinais de uma boa saúde mental?"), "outros"),
            (self.extract_features("Como funciona a tecnologia de reconhecimento facial?"), "outros"),
            (self.extract_features("Explique o conceito de sustentabilidade."), "outros"),
            (self.extract_features("Quais são os passos para escrever um bom ensaio?"), "outros"),
            (self.extract_features("O que é a teoria da evolução?"), "outros"),
            (self.extract_features("Quais são as propriedades dos ácidos e bases?"), "outros"),
            (self.extract_features("Como cultivar uma horta em casa?"), "outros"),
            (self.extract_features("O que é a inteligência artificial?"), "outros"),
            (self.extract_features("Como ocorre a produção de energia em uma célula?"), "outros"),
            (self.extract_features("Quais são os benefícios da meditação?"), "outros"),
            (self.extract_features("Como posso melhorar minha memória?"), "outros"),
            (self.extract_features("O que é a psicologia positiva?"), "outros"),
            (self.extract_features("Quais são os diferentes tipos de nuvens?"), "outros"),
            (self.extract_features("Como funciona a impressão 3D?"), "outros"),
            (self.extract_features("Quais são os cuidados com a alimentação saudável?"), "outros"),
            (self.extract_features("O que é a teoria das cordas?"), "outros"),
            (self.extract_features("Como ocorre a fotossíntese nas plantas?"), "outros"),
            (self.extract_features("Quais são os sinais de uma boa liderança?"), "outros"),
            (self.extract_features("O que é a teoria da conspiração?"), "outros"),
            (self.extract_features("Como lidar com o estresse no trabalho?"), "outros"),
            (self.extract_features("O que é a resiliência?"), "outros"),
            (self.extract_features("Quais são os benefícios da leitura diária?"), "outros"),
            (self.extract_features("Como as estrelas produzem luz?"), "outros"),
            (self.extract_features("O que é a teoria da relatividade de Einstein?"), "outros"),
            (self.extract_features("Quais são as etapas do método científico?"), "outros"),
            (self.extract_features("Como escolher a carreira certa?"), "outros"),
            (self.extract_features("Quais são os impactos da poluição ambiental?"), "outros"),
            (self.extract_features("O que é a teoria do caos?"), "outros"),
            (self.extract_features("Como se formam os arco-íris?"), "outros")
        ]
        classifier = NaiveBayesClassifier.train(training_data)

        return classifier
    
    def predict_intent(self, message, classifier):
        features = self.extract_features(message)
        return classifier.classify(features)